CREATE DATABASE IF NOT EXISTS ERP_LAPAZ;

DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE USUARIOS (
    `IDUSUARIO` INT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(20) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(200) NOT NULL,
    `PERMISSION` INT NOT NULL DEFAULT 0,
    PRIMARY KEY(IDUSUARIO)
);

INSERT INTO
    USUARIOS (USERNAME, PASSWORD, PERMISSION)
VALUES
    (
        "admin",
        "$2a$10$Ejbqi/IDNaZ7sCntKjC5XOxNsY5.x.Er7WQipz2bb0qtRLNBd7RLq",
        10
    ),
    -- lapaz
    (
        "lucaslapaz",
        "$2a$10$8dMh5cbflvikcPyi5.YenuYsqDjePOjPD4g86K9OoDIjAsJor/rXC",
        5
    ),
    -- 123
    (
        "jorgebento",
        "$2a$10$L81CaPmBCPvsxpskuSI1k.LQ8uJmqrP5JLMpFpzr6CbI4eO7cTHou",
        0
    );

-- 321
--------------------- TESTE QUALQUER ------------------------
DROP TABLE IF EXISTS TESTES;

CREATE TABLE TESTES(
    `TEXTO` VARCHAR(200) NOT NULL,
    `ID_USUARIO` INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(IDUSUARIO)
);

------------------- PRODUTOS --------------------------
DROP TABLE IF EXISTS PRODUTOS;

CREATE TABLE PRODUTOS(
    `IDPRODUTO` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(100) NOT NULL,
    `VALOR` FLOAT DEFAULT 0,
    `ESTOQUE` INT DEFAULT 0,
    `UNIDADE_MEDIDA` ENUM('KG', 'UNID', 'GRAMA') NOT NULL DEFAULT 'UNID',
    PRIMARY KEY (IDPRODUTO)
);

INSERT INTO
    PRODUTOS (NOME, VALOR, ESTOQUE)
VALUES
    ('COCA-COLA 2L', 8.5, 132);

------------------- TIPOS DE FICHAS --------------------------
DROP TABLE IF EXISTS FICHAS_TIPO;

CREATE TABLE FICHAS_TIPO(
    IDTIPO INT NOT NULL AUTO_INCREMENT,
    NOMEIMAGEM VARCHAR(300) NOT NULL,
    PATHIMAGEM VARCHAR(300) NOT NULL UNIQUE,
    FORMATO VARCHAR(10) NOT NULL,
    NOMEFICHA VARCHAR(40) NOT NULL UNIQUE,
    PRIMARY KEY (IDTIPO)
);

------------------- FICHAS --------------------------

DROP TABLE IF EXISTS FICHAS;

CREATE TABLE FICHAS (
    IDFICHA INT NOT NULL AUTO_INCREMENT,
    NUMERO INT NOT NULL,
    ID_TIPO INT NOT NULL,
    FOREIGN KEY (IDFICHA) REFERENCES FICHAS_TIPO(IDTIPO)
);

-------------------------------------------------------

DROP TABLE IF EXISTS PRODUTOS_FICHAS_ABERTAS;

DROP TABLE IF EXISTS VENDAS;

DROP TABLE IF EXISTS PRODUTOS_VENDAS;